name: GITHUB PAGES DEPLOY

on: [workflow_call, workflow_dispatch]
permissions: # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
  contents: read
  pages: write
  id-token: write

concurrency: # Allow one concurrent deployment
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        architecture: [x64]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Use Nodejs ${{ matrix.node-version }} - ${{ matrix. architecture }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: RUN YARN INSTALL
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: RUN YARN BUILD
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - name: RUN SETUP PAGES
        uses: peaceiris/actions-gh-pages@v3

      - name: RUN UPLOAD ARTIFACT
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist # Upload entire repository

      - name: RUN DEPLOY TO GITHUB-PAGES
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: thiagosaud.dev
