name: LINTERS

on:
  pull_request:
    branches:
      - "release/*"
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  linters:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        architecture: [x64]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Nodejs ${{ matrix.node-version }} - ${{ matrix. architecture }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: CACHE NODE.JS MODULES
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - name: RUN YARN INSTALL
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: RUN COMMITLINT
        uses: borales/actions-yarn@v4
        with:
          cmd: commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: RUN BRANCHLINT
        uses: lekterable/branchlint-action@2.0.0
        with:
          allowed: |
            /release\//i
          errorMessage: "Branches with the name are not allowed."

      - name: RUN PRETTIER CHECK
        uses: borales/actions-yarn@v4
        with:
          cmd: prettier:check

      - name: RUN STYLELINT
        uses: borales/actions-yarn@v4
        with:
          cmd: stylelint:check

      - name: RUN ESLINT
        uses: borales/actions-yarn@v4
        with:
          cmd: lint
